mode = "dark"

accent = "#7aa2f7"

bg = "#1a1b26"
dark_bg = "#13141c"
darker_bg = "#0e0e14"
lighter_bg = "#24283b"
selection = "#292e42"
muted = "#414868"
dark_fg = "#565f89"
fg = "#a9b1d6"
light_fg = "#b4bee6"
bright_fg = "#c0caf5"

red = "#f7768e"
yellow = "#e0af68"
orange = "#eb927b"
green = "#9ece6a"
cyan = "#449dab"
blue = "#7aa2f7"
magenta = "#ad8ee6"
brown = "#75493d"

bright_red = "#ff7a93"
bright_yellow = "#ff9e64"
bright_green = "#b9f27c"
bright_cyan = "#0db9d7"
bright_blue = "#7da6ff"
bright_magenta = "#bb9af7"
