mode = "dark"

accent = "#7daea3"

bg = "#282828"
dark_bg = "#1e1e1e"
darker_bg = "#161616"
lighter_bg = "#3c3836"
selection = "#504945"
muted = "#665c54"
dark_fg = "#7c6f64"
fg = "#d4be98"
light_fg = "#bdae93"
bright_fg = "#d4be98"

red = "#ea6962"
yellow = "#d8a657"
orange = "#e1875c"
green = "#a9b665"
cyan = "#89b482"
blue = "#7daea3"
magenta = "#d3869b"
brown = "#70432e"

bright_red = "#ea6962"
bright_yellow = "#d8a657"
bright_green = "#a9b665"
bright_cyan = "#89b482"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
