mode = "dark"

accent = "#89b4fa"

bg = "#1e1e2e"
dark_bg = "#161622"
darker_bg = "#101019"
lighter_bg = "#313244"
selection = "#45475a"
muted = "#585b70"
dark_fg = "#6c7086"
fg = "#cdd6f4"
light_fg = "#bac2de"
bright_fg = "#cdd6f4"

red = "#f38ba8"
yellow = "#f9e2af"
orange = "#f6b6ab"
green = "#a6e3a1"
cyan = "#94e2d5"
blue = "#89b4fa"
magenta = "#f5c2e7"
brown = "#7b5b55"

bright_red = "#f38ba8"
bright_yellow = "#f9e2af"
bright_green = "#a6e3a1"
bright_cyan = "#94e2d5"
bright_blue = "#89b4fa"
bright_magenta = "#f5c2e7"
