mode = "dark"

accent = "#dcd7ba"

bg = "#1f1f28"
dark_bg = "#17171e"
darker_bg = "#111116"
lighter_bg = "#223249"
selection = "#363646"
muted = "#54546D"
dark_fg = "#727169"
fg = "#dcd7ba"
light_fg = "#c8c093"
bright_fg = "#dcd7ba"

red = "#c34043"
yellow = "#c0a36e"
orange = "#c17158"
green = "#76946a"
cyan = "#6a9589"
blue = "#7e9cd8"
magenta = "#957fb8"
brown = "#60382c"

bright_red = "#e82424"
bright_yellow = "#e6c384"
bright_green = "#98bb6c"
bright_cyan = "#7aa89f"
bright_blue = "#7fb4ca"
bright_magenta = "#938aa9"
