mode = "dark"

accent = "#faa968"

bg = "#05182e"
dark_bg = "#031222"
darker_bg = "#020c17"
lighter_bg = "#0a2540"
selection = "#134e5a"
muted = "#2a6b78"
dark_fg = "#3f8f8a"
fg = "#f6dcac"
light_fg = "#a7c9c6"
bright_fg = "#f6dcac"

red = "#f85525"
yellow = "#e97b3c"
orange = "#faa968"
green = "#028391"
cyan = "#8cbfb8"
blue = "#3f8f8a"
magenta = "#3f8f8a"
brown = "#743d1e"

bright_red = "#f85525"
bright_yellow = "#e97b3c"
bright_green = "#028391"
bright_cyan = "#8cbfb8"
bright_blue = "#faa968"
bright_magenta = "#3f8f8a"
